// Generated by CoffeeScript 1.6.3
var home, tweet, tweetStory, user, webcam, youtubeStory;

var users = require('./users')
  , premiere = require('./premiere');

function home(req, res) {
    return res.render('index', {
        title: 'What Matters Most'
    });
};

function tweet(req, res) {
    return res.render('tweet');
}

function webcam(req, res) {
    return res.render('webcam');
}

exports.create = function(app) {
    app.get('/', home);
    users.create(app);
    premiere.create(app);
};
